import type { Metadata } from "next";
import { Nav, Scrubber, Footer } from "@/components/Chrome";

export const metadata: Metadata = {
  title: "Privacy Policy — Rift Music App",
  description: "Privacy Policy for Rift Music App, the native Mac YouTube Music client.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <>
      <div className="aurora" aria-hidden>
        <div className="glow-wrap wrap-a"><div className="glow glow-a" /></div>
        <div className="glow-wrap wrap-b"><div className="glow glow-b" /></div>
        <div className="glow-wrap wrap-c"><div className="glow glow-c" /></div>
      </div>

      <Nav />
      <Scrubber />

      <main>
        <section className="rail chorus" style={{ paddingTop: 140, paddingBottom: 100 }}>
          <p className="eyebrow accent">Privacy</p>
          <h1 className="serif" style={{ fontSize: "clamp(2.6rem,6vw,4.4rem)" }}>Privacy Policy.</h1>
          <p className="lede">Last updated: August 2026</p>

          <div className="prose" style={{ marginTop: 60, display: "flex", flexDirection: "column", gap: 24, fontSize: "1.1rem", lineHeight: 1.6, color: "var(--fg-dim)" }}>
            <p>
              This Privacy Policy describes how Rift Music App (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) handles your data. Rift Music App is an independent, open-source macOS client for YouTube Music. Our core philosophy is that your data belongs to you.
            </p>
            
            <h3 style={{ color: "var(--fg)", fontSize: "1.3rem", marginTop: 24 }}>1. No Telemetry or Remote Data Collection</h3>
            <p>
              We do not collect, store, transmit, or process any telemetry, analytics, or personal usage data on our own servers. Rift Music App does not have a backend server for user data. Everything the app does happens directly between your macOS device and Google/YouTube&apos;s servers.
            </p>

            <h3 style={{ color: "var(--fg)", fontSize: "1.3rem", marginTop: 24 }}>2. Interaction with Third-Party Services</h3>
            <p>
              To provide its core functionality, Rift Music App connects directly to YouTube Music and Google APIs. 
              By logging into Rift Music App, you are authenticating directly with Google. We never see, intercept, or store your passwords. Authentication tokens are stored securely in your local macOS Keychain.
            </p>
            <p>
              Because Rift Music App acts as a client for YouTube Music, your use of the app is also governed by the <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer" style={{color: "var(--fg)", textDecoration: "underline", textUnderlineOffset: 4}}>Google Privacy Policy</a>. We encourage you to review it to understand how Google handles your data when you use YouTube services.
            </p>

            <h3 style={{ color: "var(--fg)", fontSize: "1.3rem", marginTop: 24 }}>3. Local Data Storage</h3>
            <p>
              All data generated by Rift Music App—including your preferences, cached artwork, offline music downloads, listening history, and local listening statistics—is stored strictly locally on your device. You have full ownership of this data and can delete it at any time by clearing the app&apos;s cache or uninstalling the app.
            </p>

            <h3 style={{ color: "var(--fg)", fontSize: "1.3rem", marginTop: 24 }}>4. Security</h3>
            <p>
              We prioritize the security of your local data by relying on macOS&apos;s native security features, such as the Keychain for sensitive authentication tokens. The app communicates with external services exclusively over secure HTTPS connections.
            </p>

            <h3 style={{ color: "var(--fg)", fontSize: "1.3rem", marginTop: 24 }}>5. Changes to This Policy</h3>
            <p>
              We may update this Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. The updated version will be indicated by the &quot;Last updated&quot; date.
            </p>

            <h3 style={{ color: "var(--fg)", fontSize: "1.3rem", marginTop: 24 }}>6. Contact Us</h3>
            <p>
              If you have any questions or concerns about this Privacy Policy, please open an issue on our official GitHub repository.
            </p>
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}
